#!/bin/bash

## Description: Run pnpm inside the web container in the root at the project (Use -C to manage the current working directory)
## Usage: pnpm [flags] [args]
## Example: "ddev pnpm i[nstall]" or "ddev pnpm add learna" or "ddev pnpm -C working/directory add learna"

ddev exec pnpm "$@"
